name: Autometed Tests

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable
      - name: Install Dependencies
        run: pip install -r requierements.txt
      - name: Run Tests
        run: pytest

